name: PoszukiwaczeDiamentow
version: '${project.version}'
main: me.mimi.wincentplugin.WincentPlugin
api-version: 1.18
authors: [ mimiwester ]
commands:
  pd:
    description: Basic command to plugins.